//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int IdAppointment { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Time { get; set; }
        public int Duration { get; set; }
        public string Remark { get; set; }
        public int ClientIdClient { get; set; }
        public int StatusIdStatus { get; set; }
        public int CompanyIdCompany { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Status Status { get; set; }
        public virtual Company Company { get; set; }
    }
}
