//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OICAR_Desktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker_Specializations
    {
        public int IdWorker_Specializations { get; set; }
        public int WorkerIdWorker { get; set; }
        public int SpecializationIdSpecialization { get; set; }
    
        public virtual Worker Worker { get; set; }
        public virtual Specialization Specialization { get; set; }
    }
}
