//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OICAR_Desktop.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Service_Type> Service_Type { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    
        public virtual ObjectResult<GetAppointmentForDataGrid_Result> GetAppointmentForDataGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAppointmentForDataGrid_Result>("GetAppointmentForDataGrid");
        }
    }
}
